insert into stock_master (symbol, name) values ('TSLA', 'Tesla Inc.');
insert into stock_master (symbol, name) values ('IBIO', 'iBio Inc.');
insert into stock_master (symbol, name) values ('NAT',  'Nordic American Tankers Limited');
insert into stock_master (symbol, name) values ('FFIV', 'F5 Networks Inc.');
insert into stock_master (symbol, name) values ('MRNA', 'Moderna Inc.');
insert into stock_master (symbol, name) values ('KSS',  'Kohls Corporation');
insert into stock_master (symbol, name) values ('NVDA', 'NVIDIA Corporation');
insert into stock_master (symbol, name) values ('USO',  'United States Oil Fund LP');
insert into stock_master (symbol, name) values ('AXSM', 'Axsome Therapeutics Inc.');
insert into stock_master (symbol, name) values ('VISL', 'Vislink Technologies Inc.');
insert into stock_master (symbol, name) values ('CGC',  'Canopy Growth Corporation');
insert into stock_master (symbol, name) values ('SBUX', 'Starbucks Corporation');
insert into stock_master (symbol, name) values ('BYND', 'Beyond Meat Inc.');
insert into stock_master (symbol, name) values ('YTEN', 'Yield10 Bioscience Inc.');
insert into stock_master (symbol, name) values ('UCO',  'ProShares Ultra Bloomberg Crude Oil');
insert into stock_master (symbol, name) values ('LYV',  'Live Nation Entertainment.');
insert into stock_master (symbol, name) values ('CCL',  'Carnival Corporation & Plc');
insert into stock_master (symbol, name) values ('UAVS', 'AgEagle Aerial Systems Inc.');
insert into stock_master (symbol, name) values ('BBBY', 'Bed Bath & Beyond Inc.');
insert into stock_master (symbol, name) values ('COTY', 'Coty Inc.');
insert into stock_master (symbol, name) values ('WORK', 'Slack Technologies Inc.');
insert into stock_master (symbol, name) values ('AMD',  'Advanced Micro Devices Inc.');
insert into stock_master (symbol, name) values ('RCL',  'Royal Caribbean Cruises Ltd.');
insert into stock_master (symbol, name) values ('QTNT', 'Quotient Limited');
insert into stock_master (symbol, name) values ('GOOG', 'Alphabet Inc.');
insert into stock_master (symbol, name) values ('NXPI', 'NXP Semiconductors N.V.');
insert into stock_master (symbol, name) values ('VSTM', 'Verastem Inc.');
insert into stock_master (symbol, name) values ('GNC',  'GNC Holdings Inc.');
insert into stock_master (symbol, name) values ('TNP',  'Tsakos Energy Navigation Limited');
insert into stock_master (symbol, name) values ('AIM',  'AIM ImmunoTech Inc.');
